// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -srcdir . types_sctp.go

package sctp_go

type SCTPAssocChange struct {
	Type             uint16
	Flags            uint16
	Length           uint32
	State            uint16
	Error            uint16
	Outbound_streams uint16
	Inbound_streams  uint16
	AssocId         int32
}
type SCTPPAddrChange struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	Aaddr    SockAddrStorage
	State    int32
	Error    int32
	AssocId int32
}
type SCTPRemoteError struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	Error    uint16
	AssocId int32
}
type SCTPSendFailed struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	Error    uint32
	Info     SCTPSndRcvInfo
	AssocId int32
}
type SCTPShutdownEvent struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	AssocId int32
}
type SCTPAdaptationEvent struct {
	Type           uint16
	Flags          uint16
	Length         uint32
	Adaptation_ind uint32
	AssocId       int32
}
type SCTPPDApiEvent struct {
	Type       uint16
	Flags      uint16
	Length     uint32
	Indication uint32
	AssocId   int32
	Stream     uint32
	Seq        uint32
}
type SCTPAuthKeyEvent struct {
	Type         uint16
	Flags        uint16
	Length       uint32
	Keynumber    uint16
	Altkeynumber uint16
	Indication   uint32
	AssocId     int32
}
type SCTPSenderDryEvent struct {
	Dry_type     uint16
	Dry_flags    uint16
	Dry_length   uint32
	Dry_AssocId int32
}
type SCTPStreamResetEvent struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	AssocId int32
}
type SCTPAssocResetEvent struct {
	Type       uint16
	Flags      uint16
	Length     uint32
	AssocId   int32
	Local_tsn  uint32
	Remote_tsn uint32
}
type SCTPStreamChangeEvent struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	AssocId int32
	Instrms  uint16
	Outstrms uint16
}
type SCTPNotification [148]byte
type SCTPNotificationHeader struct {
	Type   uint16
	Flags  uint16
	Length uint32
}
type SCTPRTOInfo struct {
	AssocId int32
	Initial  uint32
	Max      uint32
	Min      uint32
}
type SCTPAssocParams struct {
	AssocId                 int32
	Asocmaxrxt               uint16
	Number_peer_destinations uint16
	Peer_rwnd                uint32
	Local_rwnd               uint32
	Cookie_life              uint32
}
type SCTPSetAdaptation struct {
	Adaptation_ind uint32
}
type SCTPPeerAddrParams struct {
	AssocId   int32
	Pad_cgo_0  [128]byte
	Hbinterval uint32
	Pathmaxrxt uint16
	Pad_cgo_1  [16]byte
	Dscp       uint8
	Pad_cgo_2  [1]byte
}
type SCTPAuthChunk struct {
	Chunk uint8
}
type SCTPHmacAlgo struct {
	Num_idents uint32
}
type SCTPAuthKey struct {
	AssocId  int32
	Keynumber uint16
	Keylength uint16
}
type SCTPAuthKeyId struct {
	AssocId  int32
	Keynumber uint16
	Pad_cgo_0 [2]byte
}
type SCTPSackInfo struct {
	AssocId int32
	Delay    uint32
	Freq     uint32
}
type SCTPAssocValue struct {
	Id    int32
	Value uint32
}
type SCTPStreamValue struct {
	AssocId     int32
	Stream_id    uint16
	Stream_value uint16
}
type SCTPPeerAddrInfo struct {
	AssocId  int32
	Pad_cgo_0 [128]byte
	State     int32
	Cwnd      uint32
	Srtt      uint32
	Rto       uint32
	Mtu       uint32
}
type SCTPStatus struct {
	AssocId            int32
	State               int32
	Rwnd                uint32
	Unackdata           uint16
	Penddata            uint16
	Instrms             uint16
	Outstrms            uint16
	Fragmentation_point uint32
	Primary             SCTPPeerAddrInfo
}
type SCTPAuthChunks struct {
	AssocId         int32
	Number_of_chunks uint32
}
type SCTPAssocIds struct {
	Number_of_ids uint32
}
type SCTPGetAddrs struct {
	AssocId int32
	Addr_num uint32
}
type SCTPAssocStats struct {
	AssocId       int32
	Obs_rto_ipaddr SockAddrStorage
	Maxrto         uint64
	Isacks         uint64
	Osacks         uint64
	Opackets       uint64
	Ipackets       uint64
	Rtxchunks      uint64
	Outofseqtsns   uint64
	Idupchunks     uint64
	Gapcnt         uint64
	Ouodchunks     uint64
	Iuodchunks     uint64
	Oodchunks      uint64
	Iodchunks      uint64
	Octrlchunks    uint64
	Ictrlchunks    uint64
}
type SCTPPeelOffArg struct {
	Associd int32
	Sd      int32
}
type SCTPPeelOffFlagsArg struct {
	Arg   SCTPPeelOffArg
	Flags uint32
}
type SCTPPeerAddrThresholds struct {
	AssocId   int32
	Address    SockAddrStorage
	Pathmaxrxt uint16
	Pathpfthld uint16
	Pad_cgo_0  [4]byte
}
type SCTPPRStatus struct {
	AssocId         int32
	Sid              uint16
	Policy           uint16
	Abandoned_unsent uint64
	Abandoned_sent   uint64
}
type SCTPDefaultPRInfo struct {
	AssocId  int32
	Value     uint32
	Policy    uint16
	Pad_cgo_0 [2]byte
}
type SCTPInfo struct {
	Tag                   uint32
	State                 uint32
	Rwnd                  uint32
	Unackdata             uint16
	Penddata              uint16
	Instrms               uint16
	Outstrms              uint16
	Fragmentation_point   uint32
	Inqueue               uint32
	Outqueue              uint32
	Overall_error         uint32
	Max_burst             uint32
	Maxseg                uint32
	Peer_rwnd             uint32
	Peer_tag              uint32
	Peer_capable          uint8
	Peer_sack             uint8
	X__reserved1          uint16
	Isacks                uint64
	Osacks                uint64
	Opackets              uint64
	Ipackets              uint64
	Rtxchunks             uint64
	Outofseqtsns          uint64
	Idupchunks            uint64
	Gapcnt                uint64
	Ouodchunks            uint64
	Iuodchunks            uint64
	Oodchunks             uint64
	Iodchunks             uint64
	Octrlchunks           uint64
	Ictrlchunks           uint64
	P_address             SockAddrStorage
	P_state               int32
	P_cwnd                uint32
	P_srtt                uint32
	P_rto                 uint32
	P_hbinterval          uint32
	P_pathmaxrxt          uint32
	P_sackdelay           uint32
	P_sackfreq            uint32
	P_ssthresh            uint32
	P_partial_bytes_acked uint32
	P_flight_size         uint32
	P_error               uint16
	X__reserved2          uint16
	S_autoclose           uint32
	S_adaptation_ind      uint32
	S_pd_point            uint32
	S_nodelay             uint8
	S_disable_fragments   uint8
	S_v4mapped            uint8
	S_frag_interleave     uint8
	S_type                uint32
	X__reserved3          uint32
}
type SCTPResetStreams struct {
	AssocId       int32
	Flags          uint16
	Number_streams uint16
}
type SCTPAddStreams struct {
	AssocId int32
	Instrms  uint16
	Outstrms uint16
}
type SCTPEvent struct {
	AssocId  int32
	Type      uint16
	On        uint8
	Pad_cgo_0 [1]byte
}
