// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -srcdir . types_sctp.go

package sctp_go

type InAddr struct {
	Addr uint32
}
type In6Addr struct {
	X__in6_u [16]byte
}
type SockAddrIn6 struct {
	Family   uint16
	Port     uint16
	Flowinfo uint32
	Addr     In6Addr
	Scope_id uint32
}
type SockAddrIn struct {
	Family uint16
	Port   uint16
	Addr   InAddr
	Zero   [8]uint8
}
type SockAddr struct {
	Family uint16
	Data   [14]int8
}
type SockAddrStorage struct {
	Family        uint16
	X__ss_padding [118]int8
	X__ss_align   uint64
}
type SCTPAssocId int32
type SCTPInitMsg struct {
	Num_ostreams   uint16
	Max_instreams  uint16
	Max_attempts   uint16
	Max_init_timeo uint16
}
type SCTPSndRcvInfo struct {
	Stream     uint16
	Ssn        uint16
	Flags      uint16
	Ppid       uint32
	Context    uint32
	Timetolive uint32
	Tsn        uint32
	Cumtsn     uint32
	Assoc_id   int32
}
type SCTPSndInfo struct {
	Sid      uint16
	Flags    uint16
	Ppid     uint32
	Context  uint32
	Assoc_id int32
}
type SCTPRcvInfo struct {
	Sid      uint16
	Ssn      uint16
	Flags    uint16
	Ppid     uint32
	Tsn      uint32
	Cumtsn   uint32
	Context  uint32
	Assoc_id int32
}
type SCTPNxtInfo struct {
	Sid      uint16
	Flags    uint16
	Ppid     uint32
	Length   uint32
	Assoc_id int32
}
type SCTPPrInfo struct {
	Policy uint16
	Value  uint32
}
type SCTPAuthInfo struct {
	Keynumber uint16
}
type SCTPCmsgData [32]byte
type SCTPAssocChange struct {
	Type             uint16
	Flags            uint16
	Length           uint32
	State            uint16
	Error            uint16
	Outbound_streams uint16
	Inbound_streams  uint16
	Assoc_id         int32
}
type SCTPPAddrChange struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	Aaddr    SockAddrStorage
	State    int32
	Error    int32
	Assoc_id int32
}
type SCTPRemoteError struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	Error    uint16
	Assoc_id int32
}
type SCTPSendFailed struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	Error    uint32
	Info     SCTPSndRcvInfo
	Assoc_id int32
}
type SCTPShutdownEvent struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	Assoc_id int32
}
type SCTPAdaptationEvent struct {
	Type           uint16
	Flags          uint16
	Length         uint32
	Adaptation_ind uint32
	Assoc_id       int32
}
type SCTPPDApiEvent struct {
	Type       uint16
	Flags      uint16
	Length     uint32
	Indication uint32
	Assoc_id   int32
	Stream     uint32
	Seq        uint32
}
type SCTPAuthKeyEvent struct {
	Type         uint16
	Flags        uint16
	Length       uint32
	Keynumber    uint16
	Altkeynumber uint16
	Indication   uint32
	Assoc_id     int32
}
type SCTPSenderDryEvent struct {
	Dry_type     uint16
	Dry_flags    uint16
	Dry_length   uint32
	Dry_assoc_id int32
}
type SCTPStreamResetEvent struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	Assoc_id int32
}
type SCTPAssocResetEvent struct {
	Type       uint16
	Flags      uint16
	Length     uint32
	Assoc_id   int32
	Local_tsn  uint32
	Remote_tsn uint32
}
type SCTPStreamChangeEvent struct {
	Type     uint16
	Flags    uint16
	Length   uint32
	Assoc_id int32
	Instrms  uint16
	Outstrms uint16
}
type SCTPEventSubscribe struct {
	Data_io_event          uint8
	Association_event      uint8
	Address_event          uint8
	Send_failure_event     uint8
	Peer_error_event       uint8
	Shutdown_event         uint8
	Partial_delivery_event uint8
	Adaptation_layer_event uint8
	Authentication_event   uint8
	Sender_dry_event       uint8
	Stream_reset_event     uint8
	Assoc_reset_event      uint8
	Stream_change_event    uint8
}
type SCTPNotification [148]byte
type SCTPNotificationHeader struct {
	Type   uint16
	Flags  uint16
	Length uint32
}
type SCTPRTOInfo struct {
	Assoc_id int32
	Initial  uint32
	Max      uint32
	Min      uint32
}
type SCTPAssocParams struct {
	Assoc_id                 int32
	Asocmaxrxt               uint16
	Number_peer_destinations uint16
	Peer_rwnd                uint32
	Local_rwnd               uint32
	Cookie_life              uint32
}
type SCTPSetPeerPrimary struct {
	Assoc_id  int32
	Pad_cgo_0 [128]byte
}
type SCTPPrimaryAddr struct {
	Assoc_id  int32
	Pad_cgo_0 [128]byte
}
type SCTPSetAdaptation struct {
	Adaptation_ind uint32
}
type SCTPPeerAddrParams struct {
	Assoc_id   int32
	Pad_cgo_0  [128]byte
	Hbinterval uint32
	Pathmaxrxt uint16
	Pad_cgo_1  [16]byte
	Dscp       uint8
	Pad_cgo_2  [1]byte
}
type SCTPAuthChunk struct {
	Chunk uint8
}
type SCTPHmacAlgo struct {
	Num_idents uint32
}
type SCTPAuthKey struct {
	Assoc_id  int32
	Keynumber uint16
	Keylength uint16
}
type SCTPAuthKeyId struct {
	Assoc_id  int32
	Keynumber uint16
	Pad_cgo_0 [2]byte
}
type SCTPSackInfo struct {
	Assoc_id int32
	Delay    uint32
	Freq     uint32
}
type SCTPAssocValue struct {
	Id    int32
	Value uint32
}
type SCTPStreamValue struct {
	Assoc_id     int32
	Stream_id    uint16
	Stream_value uint16
}
type SCTPPeerAddrInfo struct {
	Assoc_id  int32
	Pad_cgo_0 [128]byte
	State     int32
	Cwnd      uint32
	Srtt      uint32
	Rto       uint32
	Mtu       uint32
}
type SCTPStatus struct {
	Assoc_id            int32
	State               int32
	Rwnd                uint32
	Unackdata           uint16
	Penddata            uint16
	Instrms             uint16
	Outstrms            uint16
	Fragmentation_point uint32
	Primary             SCTPPeerAddrInfo
}
type SCTPAuthChunks struct {
	Assoc_id         int32
	Number_of_chunks uint32
}
type SCTPAssocIds struct {
	Number_of_ids uint32
}
type SCTPGetAddrsOld struct {
	Assoc_id int32
	Addr_num int32
	Addrs    *SockAddr
}
type SCTPGetAddrs struct {
	Assoc_id int32
	Addr_num uint32
}
type SCTPAssocStats struct {
	Assoc_id       int32
	Obs_rto_ipaddr SockAddrStorage
	Maxrto         uint64
	Isacks         uint64
	Osacks         uint64
	Opackets       uint64
	Ipackets       uint64
	Rtxchunks      uint64
	Outofseqtsns   uint64
	Idupchunks     uint64
	Gapcnt         uint64
	Ouodchunks     uint64
	Iuodchunks     uint64
	Oodchunks      uint64
	Iodchunks      uint64
	Octrlchunks    uint64
	Ictrlchunks    uint64
}
type SCTPPeelOffArg struct {
	Associd int32
	Sd      int32
}
type SCTPPeelOffFlagsArg struct {
	Arg   SCTPPeelOffArg
	Flags uint32
}
type SCTPPeerAddrThresholds struct {
	Assoc_id   int32
	Address    SockAddrStorage
	Pathmaxrxt uint16
	Pathpfthld uint16
	Pad_cgo_0  [4]byte
}
type SCTPPRStatus struct {
	Assoc_id         int32
	Sid              uint16
	Policy           uint16
	Abandoned_unsent uint64
	Abandoned_sent   uint64
}
type SCTPDefaultPRInfo struct {
	Assoc_id  int32
	Value     uint32
	Policy    uint16
	Pad_cgo_0 [2]byte
}
type SCTPInfo struct {
	Tag                   uint32
	State                 uint32
	Rwnd                  uint32
	Unackdata             uint16
	Penddata              uint16
	Instrms               uint16
	Outstrms              uint16
	Fragmentation_point   uint32
	Inqueue               uint32
	Outqueue              uint32
	Overall_error         uint32
	Max_burst             uint32
	Maxseg                uint32
	Peer_rwnd             uint32
	Peer_tag              uint32
	Peer_capable          uint8
	Peer_sack             uint8
	X__reserved1          uint16
	Isacks                uint64
	Osacks                uint64
	Opackets              uint64
	Ipackets              uint64
	Rtxchunks             uint64
	Outofseqtsns          uint64
	Idupchunks            uint64
	Gapcnt                uint64
	Ouodchunks            uint64
	Iuodchunks            uint64
	Oodchunks             uint64
	Iodchunks             uint64
	Octrlchunks           uint64
	Ictrlchunks           uint64
	P_address             SockAddrStorage
	P_state               int32
	P_cwnd                uint32
	P_srtt                uint32
	P_rto                 uint32
	P_hbinterval          uint32
	P_pathmaxrxt          uint32
	P_sackdelay           uint32
	P_sackfreq            uint32
	P_ssthresh            uint32
	P_partial_bytes_acked uint32
	P_flight_size         uint32
	P_error               uint16
	X__reserved2          uint16
	S_autoclose           uint32
	S_adaptation_ind      uint32
	S_pd_point            uint32
	S_nodelay             uint8
	S_disable_fragments   uint8
	S_v4mapped            uint8
	S_frag_interleave     uint8
	S_type                uint32
	X__reserved3          uint32
}
type SCTPResetStreams struct {
	Assoc_id       int32
	Flags          uint16
	Number_streams uint16
}
type SCTPAddStreams struct {
	Assoc_id int32
	Instrms  uint16
	Outstrms uint16
}
type SCTPEvent struct {
	Assoc_id  int32
	Type      uint16
	On        uint8
	Pad_cgo_0 [1]byte
}
